### PR TITLE
rm: anda/desktops/elementary/

### LINKED ISSUE #1954: [ULTIMATUM] anda/desktops/elementary/
Deadline: **2024-09-01**

The specs, update scripts, and anything used to build this package **will be erased** from the repository.

The RPM package will be erased too if there are security concerns.

You may help stop this by solving the issue listed below.

## Issue
- Upstream Pantheon packages are unfortunately always not in sync with Fedora's packaging pace
  - e.g. mutter support is usually not up to date from Elementary
- Pantheon Desktop has been broken and deprecated since Ultramarine 40
- Internal Fyra discussions has deemed efforts to package Pantheon unviable due to its unpopularity not justifying the difficulty to maintain its stack

### PR DESCRIPTION
**Pull request by madonuko**
No more elementary/pantheon.

close #1954

### CODE REVIEW

**Comment by lleyton** [comment]
going to backport to 41 and el9

**Review by lleyton — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|Backport failed because of merge conflicts|
|❌|el9|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2055
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10804807159) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|Backport failed because of merge conflicts|
|❌|el9|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2055
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10804807142) for details

**Comment by lleyton** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2059)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/2060)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
