### PR TITLE
Add: arduino-lint

### PR DESCRIPTION
**Pull request by Owen-sz**

### CODE REVIEW

**Review by madonuko — COMMENTED** [review]
https://developer.fyralabs.com/terra/policy#go

Try to use go2rpm instead with this?

**Comment by Owen-sz** [comment]
> https://developer.fyralabs.com/terra/policy#go
> 
> Try to use go2rpm instead with this?

What for? Does what I have not work for something?

**Comment by madonuko** [comment]
> > https://developer.fyralabs.com/terra/policy#go
> > Try to use go2rpm instead with this?
> 
> What for? Does what I have not work for something?

tru, I mean… everything works so I guess

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2587)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2588)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12231541485) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2587)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2588)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12231541494) for details

**Pull request merged**
