### PR TITLE
Fix Ruffle .desktop File

### PR DESCRIPTION
**Pull request by GildedRoach**
The current Ruffle `.desktop` file does not work as it attempts to execute `ruffle` when the binary is called `ruffle_desktop`. This is an attempt to fix the spec with a corrected `.desktop` file.

### CODE REVIEW

**Review by madonuko — APPROVED** [review]
Perfect, I'll remind myself to patch this out next time.

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2583)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2584)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2581
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12218782601) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2582)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2583)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2584)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2581
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12218782597) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2581
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12218783178) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2582)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2583)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2584)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2581
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12218782622) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2582)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2583)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2584)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2581
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12218782628) for details

**Pull request merged**
