### PR TITLE
Add lightly-qt5

### PR DESCRIPTION
**Pull request by hazel-bunny**
This package was orphaned in Fedora recently. The fedora maintainers used to build this package using unmaintained sources from upstream. I have switched to a maintained fork.
Note that packaging has been done with plasma 6 in mind, so don't build it for fedora < 40. Also, merge this after I have submitted lightly-qt6.
An update script has been intentionally omitted because this is the last commit that builds against KF5. The package, however, should be rebuilt (with sources at this very commit) against every new minor version of Qt, like how breeze is rebuilt in Fedora.

### CODE REVIEW

**Review by korewaChino — DISMISSED** [review]

**Comment by madonuko** [comment]
`update.rhai`:
```ts
let repos = get("https://repology.org/api/v1/project/qt").json_arr();
let branch = sh("git rev-parse --abbrev-ref HEAD", #{"stdout": "piped"}).ctx.stdout;
branch.crop(1);
branch.trim();
let vers = repos.filter(|r| r.repo == `fedora_${branch}`).map(|r| [find("^(\\d+)\\.(\\d+)\\..+$", r.version, 1), find("^(\\d+)\\.(\\d+)\\..+$", r.version, 2)]);
let ver = vers.find(|v| v[0] == "5")[1]; // assume there is only 1 package for v5.x
open_file("anda/themes/lightly-qt5/VER5.txt").write(`${ver}`); // will trig rebuild when changed
```
create a `VER5.txt` file with:
```sh
echo -n 15 > VER5.txt
```

**Comment by madonuko** [comment]
VER5.txt should have no newline

**Comment by madonuko** [comment]
actually it'll be fine, it'll cause 1 more useless rebuild, not the end of the world…

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1079)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8570139975) for details

**Pull request merged**
