### PR TITLE
feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Backport failed because of merge conflicts|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12319706912) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Backport failed because of merge conflicts|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12319706921) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Backport failed because of merge conflicts|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12319706925) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Backport failed because of merge conflicts|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12319706935) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Cherrypick failed because the selected commit (c849d89c) is empty. Did you already backport this commit? |
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12331598619) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Cherrypick failed because the selected commit (c849d89c) is empty. Did you already backport this commit? |
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12331598634) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|f41|Cherrypick failed because the selected commit (c849d89c) is empty. Did you already backport this commit? |
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2610
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12331598618) for details

**Pull request merged**
