### PR TITLE
fix(x265): bump properly

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12319707244) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12328040236) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12328040235) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12328629461) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12328629467) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12331686483) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f41:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|
|❌|el10|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to el10:<br> - [feat(ci): fix bugs with update backporting, add weekly mode, remove f39, add el10 (#2610)](https://github.com/terrapkg/packages/pull/2610)|

### Manual backport
To create the backport manually run:
```
backport --pr 2612
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12331686522) for details

**Pull request merged**
