### PR TITLE
fix: rust-sccache

### PR DESCRIPTION
**Pull request by windowsboy111**

### CODE REVIEW

**Comment by rmnscnce** [comment]
Failed pipeline on https://github.com/terrapkg/packages/actions/runs/4497434110/jobs/7913030540?pr=306#step:3:5932, please check again.

**Review by rmnscnce — COMMENTED** [review]
Still fails to build at https://github.com/terrapkg/packages/actions/runs/4501376429/jobs/7921735375?pr=306#step:3:5909

**Review by rmnscnce — CHANGES_REQUESTED** [review]
The build fails at https://github.com/terrapkg/packages/actions/runs/4520058624/jobs/7960928526?pr=306#step:3:5282.

**Comment by windowsboy111** [comment]
We waited so long that we got a new bump wwww

**Comment by windowsboy111** [comment]
I don't understand why it's taking forever to build

**Review by rmnscnce — APPROVED** [review]

**Pull request merged**
