### PR TITLE
fix: espanso

### PR DESCRIPTION
**Pull request by pointydev**

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1126
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888642669) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1126
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888644036) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1126
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888644050) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1126
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888644051) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1126
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888644037) for details

**Pull request merged**
