### PR TITLE
fix: fontviewer

### PR DESCRIPTION
**Pull request by sadlerm4**
lol

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2702)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2703)|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|❌|el10|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2700
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12426182382) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2702)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2703)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2704)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2705)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12426182395) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2702)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2704)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2705)|

### Manual backport
To create the backport manually run:
```
backport --pr 2700
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12426182364) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2702)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2703)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2704)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2705)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12426182398) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2702)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2703)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2704)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2705)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12426182383) for details

**Pull request merged**
