### PR TITLE
add: mpv-nightly

### LINKED ISSUE #727: [Request] Add mpv-git
**What software are you requesting to be packaged?**
the git version of mpv
https://mpv.io/
https://github.com/mpv-player/mpv-build

**Describe the motivation**
The reason being is that mpv usually doesn't maintain releases. An example of this is actually here
https://github.com/mpv-player/mpv/issues/11392
because of this the current version of mpv that fedora ships with has this issue as it is still stuck with `0.35.1`

Also ppl who use mpv on windows are almost always on the git version. Because of this a lot of scripts are aimed for the git version and not the release versions. While there has been cases where scripts make it backwards compatible not all do.

instances of where this happens:
https://github.com/tomasklaen/uosc/issues/672
https://github.com/po5/memo/issues/5

Hope you consider this!

edit: Fixed wrong mpv version number

### LINKED ISSUE #897: [Request] mpv 0.37 for fedora 40/rawhide
**What software are you requesting to be packaged?**
mpv 037.0 for fedora 40/rawhide or latest git from master

**Describe the motivation**
actual fedora mpv-0.37.0-1.fc40.src.rpm '$ mpv' launch from console gives error from library path mismatch, as indicated in fedora bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=2251491
https://bugzilla.redhat.com/show_bug.cgi?id=2254969

mpv: error while loading shared libraries: /usr/lib/gcc/x86_64-redhat-linux/13/../../../../lib64/libmujs.so: cannot open shared object file: No such file or directory

this is temporally fixed by manually creating an empty 13 folder after mpv and mujs-devel install:
sudo mkdir -p /usr/lib/gcc/x86_64-redhat-linux/13

A git mpv package build in terra can give successive updated binaries to test latest functionality ahead of 0.37 for fedora rawhide, so i may choose mpv from fedora or terra.

**Additional context**
Add any other context about the package request here.

### PR DESCRIPTION
**Pull request by madonuko**
close #727

### CODE REVIEW

**Review by infinitebash — CHANGES_REQUESTED** [review]
`-Dshaderc=enabled` seems to cause the build to fail. Do we need it enabled?

**Comment by madonuko** [comment]
need to also fix versioning

**Review by infinitebash — COMMENTED** [review]
lgtm. should be fine to merge once auto-updates are working.

**Comment by wyup** [comment]
a mpv-nightly with comprehensive library dependencies would indeed be a great idea, i.e: full ffmpeg-libs from rpm-fusion

**Review by lleyton — APPROVED** [review]

**Review by infinitebash — APPROVED** [review]

**Pull request merged**
