### PR TITLE
fix gamescope for older GPUs

### LINKED ISSUE #1909: [BUG] terra-gamescope crashes due to DMABUF bug
**Describe the bug**
```
gamescope: types/wlr_linux_dmabuf_v1.c:532: feedback_compile: Assertion `table_len > 0' failed
```

**To Reproduce**
1. Install terra-gamescope
2. Try to launch gamescope

**Expected behavior**
Gamescope launches properly and selects a GPU, launching successfully

**Screenshots**
image

**Affected (please complete the following information):**
 - Fedora, Ultramarine
 - Package terra-gamescope

**Additional context**
Might be caused by one of the patches,

`inxi -G` output:
```
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: N/A resolution: 1920x1080
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.1.5 renderer: AMD
    Radeon RX 580 Series (radeonsi polaris10 LLVM 18.1.6 DRM 3.57
    6.10.3-200.fc40.x86_64)
  API: Vulkan v: 1.3.283 drivers: N/A surfaces: xcb,xlib,wayland
```

### PR DESCRIPTION
**Pull request by korewaChino**
This PR patches the terra-gamescope package so that by default the SDL backend will be selected regardless of Wayland display support or not, requiring users to explicitly set `--backend=wayland` if they want to use the new Wayland backend for Gamescope, at the detriment of newer GPUs that support the Vulkan DRM modifiers feature.

Should work regardless on those aforementioned GPUs however.

Patch to work around https://github.com/ValveSoftware/gamescope/issues/1218 on older GPUs.

If this patch works we may be able to simply obsolete `gamescope-legacy`

### CODE REVIEW

**Comment by korewaChino** [comment]
Just tested this, turns out dedicated DRM sessions are still broken without legacy. Time for a better approach

**Comment by korewaChino** [comment]
Oddly enough, while this patch fixes nested sessions, turns out even without this patch Wayland and SDL backends work pretty much fine on my RX580?????????? And turns out the only problematic part here is the DRM backend, which seems to cause issues

**Comment by korewaChino** [comment]
Currently considering obsoleting gamescope-legacy with a wrapper script that just runs gamescope with the SDL backend

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1993)|
|❌|f41|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1930
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10546297944) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1992)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1993)|
|❌|f41|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1930
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10546297947) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1992)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1994)|

### Manual backport
To create the backport manually run:
```
backport --pr 1930
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10546297945) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1992)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1993)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1994)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10546297953) for details

**Pull request merged**
