### PR TITLE
chore(ci): get rid of cache buildroot

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Comment by madonuko** [comment]
[Tested this on ultramarine-pkgs](https://github.com/Ultramarine-Linux/ultramarine-pkgs/commit/f28fcde2343b120536d5c0aba030f6fb1a208489) and [seems to be working…? I don't know](https://github.com/Ultramarine-Linux/ultramarine-pkgs/actions/runs/8488461463/job/23261573455#step:6:513)

**Review by lleyton — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|frawhide|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1014
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8569010962) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|frawhide|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1014
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8569010961) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|frawhide|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1014
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8569010963) for details

**Comment by lleyton** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1076)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1077)|
|✅|frawhide|[](https://github.com/terrapkg/packages/pull/1078)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
