### PR TITLE
add: ruffle

### LINKED ISSUE #1596: [Request] Ruffle
**What software are you requesting to be packaged?**
https://ruffle.rs/

**Describe the motivation**

**Additional context**
Also include a Desktop file that handles SWF files
```
MimeType=application/x-shockwave-flash
```

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1760)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1763)|

### Manual backport
To create the backport manually run:
```
backport --pr 1754
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10146758430) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1760)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1761)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1762)|
|❌|el9|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1754
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10146758465) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1760)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1762)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1763)|

### Manual backport
To create the backport manually run:
```
backport --pr 1754
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10146758390) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1760)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1762)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1763)|

### Manual backport
To create the backport manually run:
```
backport --pr 1754
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10146758454) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1760)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1761)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1762)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1763)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10146758473) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1760)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1761)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1762)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1763)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10146758403) for details

**Pull request merged**
