### PR TITLE
Add: git runtime dep in anda.spec

### PR DESCRIPTION
**Pull request by Owen-sz**

### CODE REVIEW

**Comment by madonuko** [comment]
add mold?

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2495)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2496)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2497)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2490
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11849879630) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2495)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2496)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2497)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2490
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11849879583) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2495)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2496)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2497)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2490
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11849879624) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2490
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11849879623) for details

**Pull request merged**
