### PR TITLE
Fix manual build arch parsing

### PR DESCRIPTION
**Pull request by korewaChino**

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|frawhide|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1454
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9851658056) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|frawhide|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1454
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9851658064) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|frawhide|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1454
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9851658058) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|frawhide|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1454
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9851658465) for details

**Pull request merged**
