### PR TITLE
add: opentabletdriver-nightly

### LINKED ISSUE #1957: [BUG] OpenTabletDriver needs .NET 6, spec requires .NET 8
**Describe the bug**
OpenTabletDriver complains about not having .NET6.0 runtime installed when it was supposed to be upgraded to .NET8.0.

**To Reproduce**
1. Install '.NET 8.0 and OpenTabletDriver'
2. See error 'NETCore.App 6.0 not found'

**Expected behavior**
Run OTD with .NET 8.0 Runtime and/or SDK without having to rely on .NET 6.0 Runtimes and/or SDK.

**Affected (please complete the following information):**
 - Ultramarine 40
 - OpenTabletDriver v0.6.4.0+9f4e357910a5917ef86166c195c858c1c65b46d2

**Additional context**
.NET 6.0 has conflicting problems with .NET 8.0 (which I have talked about in #general chat of FyraLabs discord server), because of that migrating OTD to 8.0 was expected. However, today after I removed .NET 6 so I could update everything, OTD still complained about not having .NET 6.0 installed.

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by korewaChino — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1969)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1972)|

### Manual backport
To create the backport manually run:
```
backport --pr 1968
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10455569965) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1969)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1971)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1972)|

### Manual backport
To create the backport manually run:
```
backport --pr 1968
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10455569970) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1969)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1970)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1971)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1972)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10455569950) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1969)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1970)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1971)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1972)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10455569960) for details

**Pull request merged**
