### PR TITLE
Add lightly-qt6 

### PR DESCRIPTION
**Pull request by hazel-bunny**
The qt5 version of this package was orphaned in Fedora recently. The fedora maintainers used to build this package using unmaintained sources from upstream. I have switched to a maintained fork that also supports qt6.
Note that packaging has been done with plasma 6 in mind, so don't build it for fedora < 40. Also, merge this after I have submitted lightly-qt5.
An update script has been intentionally omitted because this is the first commit that builds against KF6 and subsequent commits may need manual intervention. The package, however, should be rebuilt (with sources at this very commit) against every new minor version of Qt, like how breeze is rebuilt in Fedora.

### CODE REVIEW

**Comment by korewaChino** [comment]
This won't conflict with upstream right?

**Comment by hazel-bunny** [comment]
> This won't conflict with upstream right?

Ideally, no. It should only be built for F40 and rawhide atm.

https://bugzilla.redhat.com/show_bug.cgi?id=2251940

**Comment by hazel-bunny** [comment]
Also #1073 should obsolete the old, broken and unmaintained lightly currently found upstream

**Comment by madonuko** [comment]
`update.rhai`:
```ts
let repos = get("https://repology.org/api/v1/project/qt").json_arr();
let branch = sh("git rev-parse --abbrev-ref HEAD", #{"stdout": "piped"}).ctx.stdout;
branch.crop(1);
branch.trim();
let vers = repos.filter(|r| r.repo == `fedora_${branch}`).map(|r| [find("^(\\d+)\\.(\\d+)\\..+$", r.version, 1), find("^(\\d+)\\.(\\d+)\\..+$", r.version, 2)]);
let ver = vers.find(|v| v[0] == "6")[1]; // assume there is only 1 package for v6.x
open_file("anda/themes/lightly-qt6/VER6.txt").write(`${ver}`); // will trig rebuild when changed
```
create a `VER6.txt` file with:
```sh
echo -n 6 > VER6.txt
```

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1080)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8570174566) for details

**Pull request merged**
