### PR TITLE
fix: elementary-files

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1830)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1832)|
|❌|el9|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1828
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10234509487) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1830)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1831)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1832)|
|❌|el9|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1828
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10234509474) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1830)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1831)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1832)|
|❌|el9|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1828
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10234509469) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1830)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1831)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1832)|
|❌|el9|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1828
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10234509475) for details

**Pull request merged**
