### PR TITLE
fix: rpi-utils

### PR DESCRIPTION
**Pull request by sadlerm4**
Change %files list to match upstream changes - new piolib binary called `apitest` and `dpi_interlace` was renamed to `dpi_csync`. Also split utils into subpackages.

### CODE REVIEW

**Comment by sadlerm4** [comment]
I'm not sure if there are macros to compress manpages? I'll need to fix that before merging.

**Comment by madonuko** [comment]
> I'm not sure if there are macros to compress manpages? I'll need to fix that before merging.

not that I'm aware of

**Comment by sadlerm4** [comment]
I don't know why it's failing ahhh

**Comment by madonuko** [comment]
for some reasons those man files are not getting installed

**Comment by sadlerm4** [comment]
I fixed the missing manpage (/usr/share/man/man2/dtoverlay.2) but the other files clearly exist, even though rpmbuild thinks they don't

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2661)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2662)|
|❌|el10|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 2650
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12367243988) for details

**Pull request merged**
