### PR TITLE
add codecs to mesa on terra-extras

### PR DESCRIPTION
**Pull request by korewaChino**
**What software is being packaged here?**
The name of the software and link to website (if it exists) and source code (if available).

**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?

**Additional context**
Add any other context about the package submission here. Link to any relavent issues.

### CODE REVIEW

**Comment by korewaChino** [comment]
On another note: why is Mesa also on standard Terra? It's supposed to only be in terra-extras.

I will be removing this using this script.

```bash
subatomic-cli pkg list terra41 | grep -v freeworld | grep mesa | subatomic-cli pkg rm terra41
```

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|✅|frawhide|[](https://github.com/terrapkg/packages/pull/2739)|

### Manual backport
To create the backport manually run:
```
backport --pr 2733
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12482692521) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|❌|frawhide|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2733
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12482692485) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|
|✅|frawhide|[](https://github.com/terrapkg/packages/pull/2739)|

### Manual backport
To create the backport manually run:
```
backport --pr 2733
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12482692484) for details

**Pull request merged**
