### PR TITLE
add: google-black-cursor-theme

### PR DESCRIPTION
**Pull request by ghost**
idk if it works first try

### CODE REVIEW

**Comment by ghost** [comment]
These cursors are distributed a bit differently, instead of providing a file with every color combination, it just has the individual archives for each color. I am not sure if it would be possible to provide all colors as a single package. As of now, I just did the black cursors.

**Review by madonuko — APPROVED** [review]

**Comment by nothingneko** [comment]
Please sign and force push your commits

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1430)|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1274
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9816708008) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1430)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1431)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9816707989) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1430)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1431)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9816707990) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1430)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1431)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9816707983) for details

**Pull request merged**
