### PR TITLE
add: mt8183 kernel

### PR DESCRIPTION
**Pull request by infinitebash**

### CODE REVIEW

**Review by madonuko — DISMISSED** [review]

**Comment by madonuko** [comment]
might need to fix terrapkg/builders

**Comment by infinitebash** [comment]
> might need to fix terrapkg/builders

doing that now

**Comment by lleyton** [comment]
reminder to self to disable lfs on jobs where it isn't required

**Comment by lleyton** [comment]
reminder to self no. 2, do we need to merge any other configs besides fedora-aarch (debug?)

**Comment by lleyton** [comment]
This PR is dead, see https://github.com/FyraLabs/kaibutsu

**Pull request closed without merging**
