### PR TITLE
rm: moby-engine

### PR DESCRIPTION
**Pull request by madonuko**
retired since it's readily available in Fedora.

### CODE REVIEW

**Comment by nothingneko** [comment]
will this be a smooth upgrade?

**Comment by korewaChino** [comment]
probably, but we have this package because Fedora's containerd and moby-engine packages are slower to update sometimes due to lack of maintainers so I don't know about this PR

personally against this because I fear Fedora will abandon the package again in favor of docker-podman shim

**Review by korewaChino — APPROVED** [review]
actually we can deal with that later, we'll keep containerd and the other docker subpackages up though

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2179)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2180)|
|❌|f41|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2144
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11182278127) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2179)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2180)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2181)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11182278138) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2179)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2180)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2181)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11182278102) for details

**Pull request merged**
