### PR TITLE
fix(stardust-telescope): stardust XR deps

### PR DESCRIPTION
**Pull request by Owen-sz**

### CODE REVIEW

**Comment by madonuko** [comment]
bump release?

**Comment by Owen-sz** [comment]
Changed title, that what you wanted?

**Comment by madonuko** [comment]
image
Bump this to `2%?dist`

**Comment by Owen-sz** [comment]
Oh, done.

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2408)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2409)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2410)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2411)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11514187948) for details

**Pull request merged**
