### PR TITLE
fix: get `click` partially working

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Comment by windowsboy111** [comment]
> partially

So… A draft PR?

**Comment by cat-master21** [comment]
Well I took some time to see if I could immediately get it working but Fedora needs another debian package (I think) or it's a bug upstream about a file not existing.

**Comment by lleyton** [comment]
hmm, in order to get rpmbuild to pack this locally, I have to comment out the following files:

```
%{_sysconfdir}/dbus-1/system.d/com.lomiri.click.conf
%dir %{_libdir}/click
%dir %{_libexecdir}/click
%{_libexecdir}/click/click-service
%{_datadir}/dbus-1/system-services/com.lomiri.click.service
```

**Comment by windowsboy111** [comment]
The `%configure` thingy kinda reminds me of 
```sh
$ rpmlint -e configure-without-libdir-spec
configure-without-libdir-spec:
A configure script is run without specifying the libdir. configure options
must be augmented with something like --libdir=%{_libdir} whenever the script
supports it.
```

**Comment by cat-master21** [comment]
@windowsboy111 https://github.com/terrapkg/packages/commit/6b84f2bd2e0d38e3c9c0b0a585e90c4c5cb4acc2 is the issue, it downgraded the commit there are a lot of changes: https://gitlab.com/ubports/development/core/click/-/compare/0.5.0...main?from_project_id=25034025&straight=false

**Pull request merged**
