### PR TITLE
fix: nim-nightly

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by lleyton — APPROVED** [review]

**Comment by lleyton** [comment]
backport needed?

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1242)|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1244)|

### Manual backport
To create the backport manually run:
```
backport --pr 1238
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9012495920) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1242)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1243)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1244)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9012495961) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1243)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1244)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9012495918) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1243)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1244)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9012495931) for details

**Pull request merged**
