### PR TITLE
Add klassy

### PR DESCRIPTION
**Pull request by hazel-bunny**
Please build for rawhide and 40 only, this is for plasma 6

### CODE REVIEW

**Comment by madonuko** [comment]
personally I'm impressed by how good this looks

**Comment by madonuko** [comment]
btw I don't think the `date` macro is used or is it a forgemeta thing?

Also here's the update script (save as `update.rhai`):
```ts
rpm.global("tag", gh("paulmcauley/klassy"));
if rpm.changed() {
  rpm.global("date", date()); // remove if we don't need the `date` macro
  rpm.release();
}
```

**Comment by hazel-bunny** [comment]
> btw I don't think the `date` macro is used or is it a forgemeta thing?

%forgemeta thing. Most of my specs use rpmautospec and forge stuff, will submit over coming weeks.

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1062)|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1059
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8558022821) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1061)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1062)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1063)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8558022810) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1061)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1062)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1063)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8558022817) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1061)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1062)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1063)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8558022823) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1061)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1062)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1063)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8558022813) for details

**Pull request merged**
