### PR TITLE
[prismlauncher-nightly] Use system libs

### PR DESCRIPTION
**Pull request by runlevel5**

### CODE REVIEW

**Review by madonuko — DISMISSED** [review]

**Comment by madonuko** [comment]
Could you also force push signed commits?

**Comment by korewaChino** [comment]
Please sign your commits.

**Comment by runlevel5** [comment]
>  Could you also force push signed commits?
Okay let me

**Comment by runlevel5** [comment]
```
$ git commit --amend -S
$ git push -f
```

Should be good now I guess

**Comment by madonuko** [comment]
> ```
> $ git commit --amend -S
> $ git push -f
> ```
> 
> Should be good now I guess

I don't think you enabled gpg signing:
```
git config --global commit.gpgsign 1
git config --global user.signingkey <insert your signing key>
```

**Comment by runlevel5** [comment]
```
$ git log --show-signature
commit 476f737fb3dfab416f8ad83098101d6a8fe9264f (HEAD -> patch-1, origin/patch-1)
Good "git" signature for 8@tle.id.au with RSA key SHA256:EJIYLZxugDIJ0Z56usDfeS5o90Ln/V0SCEGFWG+YfSM
Author: Trung Lê <8@tle.id.au>
Date:   Wed Jun 19 23:15:12 2024 +1000

    [prismlauncher-nightly] Use system libs

    Signed-off-by: Trung Lê <8@tle.id.au>
```

should be good now mate

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1378)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1379)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9594669036) for details

**Comment by madonuko** [comment]
Thank you!

**Pull request merged**
