### PR TITLE
add quirks for lenovo duet chromebooks 

### PR DESCRIPTION
**Pull request by june-fish**

### CODE REVIEW

**Comment by june-fish** [comment]
TODO: test on hardware

**Comment by lleyton** [comment]
maybe this is a better fit for Ultramarine-Linux/packages

**Comment by june-fish** [comment]
...but it works on fedora too?

**Comment by june-fish** [comment]
tested working on krane

**Comment by lleyton** [comment]
> ...but it works on fedora too?

it comes from an ultramarine repo, but I trust your judgement

**Review by lleyton — APPROVED** [review]

**Pull request merged**
