### PR TITLE
feat(mock-configs): i386 multilib support

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Comment by madonuko** [comment]
See https://github.com/terrapkg/packages/pull/1549

Also I kinda don't like how the CI works in that PR; figuring out if there's a better way

**Review by korewaChino — DISMISSED** [review]

**Review by nothingneko — DISMISSED** [review]
69 nice

**Review by nothingneko — APPROVED** [review]
lgtm

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1569
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10003655368) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1569
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10003655370) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1569
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10003655438) for details

**Comment by korewaChino** [comment]
@madonuko backport when

**Comment by madonuko** [comment]
#1573 #1574

**Pull request merged**
