### PR TITLE
Fix: Ghostty Follow packaging guidelines

### LINKED ISSUE #2801: [BUG] Ghostty incorrectly packaged
**Describe the bug**
Ghostty crashes in some cases because `cpu = baseline` flag was not added to the package like suggested

**To Reproduce**

Install Ghostty on a potentially old system

**Expected behavior**
Program does not crash on start from an illegal instruction

**Screenshots**

there is an image in the ghostty repo below
https://github.com/ghostty-org/ghostty/discussions/4210

**Affected (please complete the following information):**
 - Distro Fedora
 - Package Ghostty

**Additional context**

This is part of the packaging guidelines, and not the package
https://github.com/ghostty-org/ghostty/blob/main/PACKAGING.md#building-ghostty
`-Dcpu=baseline`

https://github.com/terrapkg/packages/blob/frawhide/anda/devs/ghostty/stable/ghostty.spec#L84-L89

### PR DESCRIPTION
**Pull request by rhodes-b**
Fixes: #2801 

all the info is in the issue please refer to that

### CODE REVIEW

**Comment by rhodes-b** [comment]
also please revert this
https://github.com/terrapkg/packages/pull/2788
GLFW build is very unstable its a developer only build that is used to determine if issues are in ghostty core or with a specific app runtime (macos uses swift native runtime while linux uses GTK)

image

**Comment by Uzaaft** [comment]
https://github.com/terrapkg/packages/pull/2788#issuecomment-2566668054

**Comment by lleyton** [comment]
> also please revert this #2788 GLFW build is very unstable its a developer only build that is used to determine if issues are in ghostty core or with a specific app runtime (macos uses swift native runtime while linux uses GTK)
> 
> image

Thanks for the info, we just yanked it from our origin mirror.

**Review by lleyton — APPROVED** [review]

**Comment by lleyton** [comment]
Thanks for the PR!

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2819)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2820)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2821)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2822)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12563527214) for details

**Pull request merged**
