### PR TITLE
bump: espanso

### PR DESCRIPTION
**Pull request by GarciaLnk**

### CODE REVIEW

**Comment by madonuko** [comment]
seems to be prerelease?

**Comment by GarciaLnk** [comment]
There's nothing that indicates that it's a pre-release, however there's been a transition in the ownership of the project, and it seems they are having some trouble with the code signing keys for the Windows and Mac apps (see https://github.com/espanso/espanso/issues/1928). But I don't think this should affect us, since we are providing a third-party package for Linux and not using their signing keys.

**Comment by madonuko** [comment]
> There's nothing that indicates that it's a pre-release

image

https://github.com/espanso/espanso/releases/tag/v2.2.2

**Comment by GarciaLnk** [comment]
Fair enough I guess, should I update the PR to just bump espanso-wayland release ver to 3 to include the fixes from https://github.com/terrapkg/packages/pull/2628/commits/5de39172b13f8e76be479b7e8ebe971b90c41c5e?

**Comment by madonuko** [comment]
Sorry, I just looked more into the history, it seems like they randomly set some versions to be pre-release for whatever reason. I'll just merge this then.

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2646)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2647)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2648)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2649)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12354370233) for details

**Pull request merged**
