### PR TITLE
Add: GLFW Builds of Ghostty, Changes to Main Specs For Compatibility

### PR DESCRIPTION
**Pull request by GildedRoach**
**NOTE:** The GLFW build of Tip currently fails due to some sort of regression. The spec sheet itself should be fine.

### CODE REVIEW

**Comment by korewaChino** [comment]
why's the GLFW version not the main version anyway?

**Comment by GildedRoach** [comment]
> why's the GLFW version not the main version anyway?

The dev claims it is unstable and bad to use, but most people prefer it and have no issues aside from a lack of features. :/

**Comment by madonuko** [comment]
https://github.com/terrapkg/packages/actions/runs/12535874658/job/34958687189?pr=2788#step:7:14480

I saw you tried to add those devel packages to buildrequires, but they unfortunately are not used. This is a limitation of the build script provided by upstream. (I spent too much time trying to get dynamic linking to work but to no avail)

**Comment by GildedRoach** [comment]
> https://github.com/terrapkg/packages/actions/runs/12535874658/job/34958687189?pr=2788#step:7:14480
> 
> I saw you tried to add those devel packages to buildrequires, but they unfortunately are not used. This is a limitation of the build script provided by upstream. (I spent too much time trying to get dynamic linking to work but to no avail)

Blegh, fun. I'll clean that up a bit then. I think I know which ones to remove.

**Comment by GildedRoach** [comment]
> https://github.com/terrapkg/packages/actions/runs/12535874658/job/34958687189?pr=2788#step:7:14480
> 
> I saw you tried to add those devel packages to buildrequires, but they unfortunately are not used. This is a limitation of the build script provided by upstream. (I spent too much time trying to get dynamic linking to work but to no avail)

In this case though, should we remove the `pkg-config` patch entirely instead of just commenting it?

**Comment by madonuko** [comment]
you could remove that, I left that there just to basically wait for some miracle to happen

**Comment by GildedRoach** [comment]
> you could remove that, I left that there just to basically wait for some miracle to happen

I will back up the current specs and unused patches to maybe revisit this, for now I will clean things up.

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2797)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2798)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2799)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2800)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12561893484) for details

**Comment by Uzaaft** [comment]
> > why's the GLFW version not the main version anyway?
> 
> The dev claims it is unstable and bad to use, but most people prefer it and have no issues aside from a lack of features. :/

Just to extend on this:
The GLFW version is not stable, and according to the creator also has memory leaks. It shouldnt be packaged. Screenshot from another GH Issue/PR:
image

**Pull request merged**
