### PR TITLE
fix: arrpc

### LINKED ISSUE #1114: [BUG] arRPC doesn't work due to ESmodule import
**Describe the bug**
When installing arRPC and enabling the arRPC service, we got an error and arRPC doesn't work.
arRPC work perfectly when running from source (with ```node src``` as the upstream repo say)

**To Reproduce**
1. Install 'arrpc'
2. See error

**Expected behavior**
The arRPC server should work and be readable by vencord 

**Screenshots**
image

**Affected (please complete the following information):**
 - Distro : Fedora 39
 - Package : srpm-macros

**Additional context**
After some searching, I have found multiple issue with package :
- This package use https://github.com/vercel/pkg to build a single binary package. This project has been deprecated and archived the  Jan 13, 2024. There is a fork (https://github.com/yao-pkg/pkg) which fix issue and add support for node 20
- This is not a big issue but the package could be bump to node 20 for better support and performance
- The main issue is this commit https://github.com/OpenAsar/arrpc/commit/cfee153ef08f1ab608eb7e26218f1b99c41b9afe which add support for older and newer node release the problem is it use ```import.meta``` which is not supported by esbuild. The solution is to use ```with``` and not ```assert``` for the JSON import. It look like this : 
image
There is no commit to revert, just this patch to apply.
Step to build : 
```
sed -i -E 's@const server[^\n]+;@async function main() {\0@' src/index.js
sed -i -E 's@server\.on[^\n]+;@\0}\nmain();@' src/index.js

# add my patch to /src/process/index.js

npm i esbuild @yao-pkg/pkg
npx esbuild --bundle --platform=node --target=node20 --outdir=dist ./src/index.js
npx pkg -t node20-linux-x64 -o arrpc  ./dist/index.js
```

### PR DESCRIPTION
**Pull request by madonuko**
Add suppport for esbuild / node20
Close #1114

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]
lgtm

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1127)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1128)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1129)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888651920) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1127)|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1129)|

### Manual backport
To create the backport manually run:
```
backport --pr 1115
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888651919) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1127)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1128)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1129)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8888651924) for details

**Pull request merged**
