### PR TITLE
add: espanso-wayland espanso-x11

### LINKED ISSUE #1095: [Request] Espanso
**What software are you requesting to be packaged?**
Espanso - Cross-platform Text Expander written in Rust
https://github.com/espanso/espanso

**Describe the motivation**
The maintainers of the software have shown interest in RPM packaging (https://github.com/espanso/espanso/issues/1948), however are unfamiliar with best practices and distribution methods. Currently, the methods to update the application on RPM distros is by using the AppImage or by manually compiling, which require manually restarting the systemd service in order to update correctly. This could be streamlined by RPM packaging.

**Additional context**
Using Terra would skip the bureaucracy of the official repos, while also being easier than making a Copr. I also believe their maintainers would be able to learn a thing or two about properly creating RPMs themselves with Terra builds in place.

Thanks,
pointy

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]
lgmt

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1101)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1102)|

### Manual backport
To create the backport manually run:
```
backport --pr 1098
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8724974302) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1099)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1101)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1102)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8724974279) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1100)|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1102)|

### Manual backport
To create the backport manually run:
```
backport --pr 1098
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8724974282) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1099)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1101)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1102)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8724974315) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1099)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1101)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1102)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8724974311) for details

**Pull request merged**
