### PR TITLE
fix(klassy): files

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f38:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|❌|f39|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f39:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1138
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8894522830) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f38:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|❌|f39|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f39:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1140)|

### Manual backport
To create the backport manually run:
```
backport --pr 1138
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8894522871) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f38:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|❌|f39|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f39:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1140)|

### Manual backport
To create the backport manually run:
```
backport --pr 1138
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8894522824) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f38:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|❌|f39|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f39:<br> - [fix: espanso (#1126)](https://github.com/terrapkg/packages/pull/1126)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1140)|

### Manual backport
To create the backport manually run:
```
backport --pr 1138
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8894522821) for details

**Pull request merged**
