### PR TITLE
add: pip-system-certs

### LINKED ISSUE #1064: [New] python-git-versioner
**What software are you requesting to be packaged?**
[python-git-versioner](https://gitlab.com/alelec/__version__)

**Describe the motivation**
Dependency for Anki 24.04

**Additional context**
Already discussed in Fyra Labs Discord

### LINKED ISSUE #1065: [New] python-pip-system-certs
**What software are you requesting to be packaged?**
[python-pip-system-certs](https://gitlab.com/alelec/pip-system-certs)

**Describe the motivation**
Dependency for Anki 24.04

**Additional context**
Already discussed in Fyra Labs Discord

### PR DESCRIPTION
**Pull request by madonuko**
close #1065 
close #1064 (not needed)

### CODE REVIEW

**Comment by madonuko** [comment]
Odd, somehow the arm builder is stuck at the dnf step

**Review by hazel-bunny — APPROVED** [review]

**Review by nothingneko — APPROVED** [review]
lgtm

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1166)|

### Manual backport
To create the backport manually run:
```
backport --pr 1075
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8922220636) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1165)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1166)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8922220658) for details

**Pull request merged**
