### PR TITLE
add: osu-mime osu-lazer

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Comment by lleyton** [comment]
funni alt account

**Comment by madonuko** [comment]
funni

**Comment by madonuko** [comment]
Ah yes why are all the commits unverified

**Comment by madonuko** [comment]
I hate gh codespaces

**Comment by lleyton** [comment]
rip lint

**Review by lleyton — APPROVED** [review]

**Comment by lleyton** [comment]
sign your commits lol

**Comment by windowsboy111** [comment]
See #195

**Pull request closed without merging**
