### PR TITLE
Update cros-keyboard-map.spec dep

### PR DESCRIPTION
**Pull request by Owen-sz**

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1923)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1924)|

### Manual backport
To create the backport manually run:
```
backport --pr 1904
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10406541717) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1921)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1922)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1923)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1924)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10406540182) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1924)|

### Manual backport
To create the backport manually run:
```
backport --pr 1904
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10406541768) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1922)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1923)|
|❌|el9|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1904
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10406541729) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1923)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1924)|

### Manual backport
To create the backport manually run:
```
backport --pr 1904
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10406541690) for details

**Pull request merged**
