### PR TITLE
add: steam

### LINKED ISSUE #2210: [Request] steam
**What software are you requesting to be packaged?**
https://steampowered.com

**Describe the motivation**
Yes, while Steam does have a Flatpak it falls into the game launchers exception category, which we can assume people are going to use the native packages for in case they want to actually use native runtimes and some advanced tools.

For example: Testing a local build of Gamescope with native Steam games, or re-using global MangoHud configs.

If we want to completely replace RPMFusion in the future this package is simply a must.

Another supporting case is that we already have `extest`, which requires a native build of Steam to be present to work to emulate XTEST.

### PR DESCRIPTION
**Pull request by korewaChino**
This shouldn't be merged with 41 or lower, since we are planning to move away entirely from RPMFusion in 42.

You should rebase this for 42 once it comes out though

### CODE REVIEW

**Comment by madonuko** [comment]
I don't think we allow sources in this repo

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2221)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2222)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2223)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2224)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11267251306) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|el10|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2211
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11267252222) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2224)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11267252214) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|el10|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2211
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11267252204) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2224)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11267252227) for details

**Comment by korewaChino** [comment]
**Revert this PR for non-rawhide now.**

https://dont-ship.it/

**Pull request merged**
