### PR TITLE
Add: Polycrystal

### PR DESCRIPTION
**Pull request by Owen-sz**

### CODE REVIEW

**Review by lleyton — CHANGES_REQUESTED** [review]
looking good so far, however, we have a stable release now + you need to install a systemd service file and use systemd macros

**Comment by Owen-sz** [comment]
> looking good so far, however, we have a stable release now + you need to install a systemd service file and use systemd macros

Sounds good, I'll update this today/tomorrow then.

**Comment by Owen-sz** [comment]
The service would need to be added to an Ultramarine preset file? I don't see it added yet.

**Comment by Owen-sz** [comment]
I assume the systemd service should be enabled by default? If that's the case, I'm not seeing the service in any UM preset yet.

**Comment by lleyton** [comment]
> I assume the systemd service should be enabled by default? If that's the case, I'm not seeing the service in any UM preset yet.

yes, but I need you to include a .service file in this package first

**Comment by Owen-sz** [comment]
Should be good now.

**Comment by Owen-sz** [comment]
I thought the systemd macros needed to point to the preset file with the service state defined, not the service file itself?

**Review by lleyton — APPROVED** [review]

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2505)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2506)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11945330778) for details

**Pull request merged**
