### PR TITLE
fix: switchboard

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1413
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9789130584) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1421)|

### Manual backport
To create the backport manually run:
```
backport --pr 1413
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9789130585) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1420)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1421)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9789130586) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1420)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1421)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9789130583) for details

**Pull request merged**
