### PR TITLE
fix: reset author and sign during backport

### PR DESCRIPTION
**Pull request by lleyton**

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1069
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8563548730) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1069
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8563548736) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1069
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8563548735) for details

**Comment by lleyton** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1070)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1071)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1072)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
