### PR TITLE
add: fontviewer

### PR DESCRIPTION
**Pull request by sadlerm4**
Small, simplistic GTK+ 3 font viewer

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2207)|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2209)|

### Manual backport
To create the backport manually run:
```
backport --pr 2205
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11239293946) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2206)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2207)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2208)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2209)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11239291964) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2207)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2208)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2209)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11239293809) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2208)|
|❌|el10|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2205
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11239295760) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2209)|

### Manual backport
To create the backport manually run:
```
backport --pr 2205
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11239293777) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2207)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2208)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2209)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11239293885) for details

**Pull request merged**
