### PR TITLE
fix(nim-nightly): fixed package name

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by lleyton — CHANGES_REQUESTED** [review]
I'm pretty sure you're gonna need obsoletes for the subpackages too

**Review by lleyton — CHANGES_REQUESTED** [review]
pretty sure dist tag isn't needed, also you might want to provides for the "broken name", just in case, see:

https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages

**Review by lleyton — CHANGES_REQUESTED** [review]
set the release in the obsoletes to be one higher than the last build of the faulty package

>  Take %{?dist} into account: When deciding what $obsEVR should be, remember that it needs to be higher than the previous Release:, including the %{?dist} suffix. Example: if the package previously had the release tag of -4.fcNN, the release specified in $obsEVR should be at least 5.

**Review by lleyton — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1108)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1109)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1110)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8771118203) for details

**Pull request merged**
