### PR TITLE
feat: rm sccache

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Comment by madonuko** [comment]
https://github.com/terrapkg/packages/actions/runs/5057164751/jobs/9075591969?pr=458#step:4:5345

SIGKILL?

**Comment by lleyton** [comment]
out of all things in Terra... it OOMs on sccache? that's a surprise

**Comment by madonuko** [comment]
https://github.com/terrapkg/packages/actions/runs/5057164751/jobs/9192186593#step:4:5175

dep source code fail? dunno

**Comment by madonuko** [comment]
LMAO new sccache version

**Review by korewaChino — APPROVED** [review]

**Pull request merged**
