### PR TITLE
fix: sbctl

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]
reviewed this from a bike. I love GitHub mobile.

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1249)|

### Manual backport
To create the backport manually run:
```
backport --pr 1248
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9048555479) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1249)|

### Manual backport
To create the backport manually run:
```
backport --pr 1248
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9048555470) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1249)|

### Manual backport
To create the backport manually run:
```
backport --pr 1248
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9048555469) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|Backport failed because of merge conflicts|
|❌|f39|Backport failed because of merge conflicts|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1249)|

### Manual backport
To create the backport manually run:
```
backport --pr 1248
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9048555473) for details

**Pull request merged**
