### PR TITLE
fix(limine): use gz tarball

### PR DESCRIPTION
**Pull request by lleyton**

### CODE REVIEW

**Review by madonuko — APPROVED** [review]
LMAO

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1052)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1053)|

### Manual backport
To create the backport manually run:
```
backport --pr 1049
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8553598038) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1051)|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1053)|

### Manual backport
To create the backport manually run:
```
backport --pr 1049
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8553598106) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1051)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1052)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1053)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8553598050) for details

**Pull request merged**
