### PR TITLE
Fix dependencies of anki-bin and anki-qt5

### PR DESCRIPTION
**Pull request by hazel-bunny**
- Fix `orjson is missing; DB operations will be slower`
- Add mpv for sounds on cards
- Add python3-qt5-webengine to anki-qt5

### CODE REVIEW

**Comment by korewaChino** [comment]
Patch fails in qt5 build, please fix your patch.

**Review by korewaChino — CHANGES_REQUESTED** [review]
Please fix the Qt 5 patch.

**Comment by hazel-bunny** [comment]
> Patch fails in qt5 build, please fix your patch.

Where are the build logs?

**Comment by korewaChino** [comment]
> > Patch fails in qt5 build, please fix your patch.
> 
> Where are the build logs?


[7_Build with Andaman.txt](https://github.com/terrapkg/packages/files/13322282/7_Build.with.Andaman.txt)

**Comment by madonuko** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/?h=anki-qt5

find the patches here

**Review by korewaChino — APPROVED** [review]

**Comment by korewaChino** [comment]
ok lgtm

**Pull request merged**
