### PR TITLE
Add cros-keyboard-map

### PR DESCRIPTION
**Pull request by Owen-sz**
Co-authored by @june-fish

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1201)|

### Manual backport
To create the backport manually run:
```
backport --pr 1199
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8956070852) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1200)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1201)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8956070853) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1200)|
|❌|f39|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1199
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8956070864) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1200)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1201)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8956070851) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|frawhide|[](https://github.com/terrapkg/packages/pull/1202)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/8956347303) for details

**Pull request merged**
