### PR TITLE
add open-in-mpv

### PR DESCRIPTION
**Pull request by june-fish**

### CODE REVIEW

**Comment by june-fish** [comment]
worked locally on my laptop running um 40, not sure why it's failing in CI

**Comment by madonuko** [comment]
> worked locally on my laptop running um 40, not sure why it's failing in CI

Rawhide is broken today, upstream issue

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1439)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1440)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9834067715) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1440)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9834067714) for details

**Pull request merged**
