### PR TITLE
Add: kvrocks

### PR DESCRIPTION
**Pull request by der-eismann**
Hey everyone, I recently stumbled upon your repository and found it very practical. I built an RPM repository for the [Apache Kvrocks](https://kvrocks.apache.org/) application since I needed it for work and thought it might make sense to include it here, since it's not really available as an RPM package anywhere and I fear the bureaucracy to get it into the Fedora repos. 

Totally fine if you don't want applications like that in your repository, I just had the recipe at hand and thought someone might like it.

### CODE REVIEW

**Comment by madonuko** [comment]
This might need `openssl-devel-engine`, but not so sure; anyway just triggered CI.

**Comment by der-eismann** [comment]
> This might need `openssl-devel-engine`

Hmm, tbh I didn't know about this package. How would I find out if it is needed? Is it enough if it builds without any issues or digging through the source code?

**Comment by madonuko** [comment]
> > This might need `openssl-devel-engine`
> 
> Hmm, tbh I didn't know about this package. How would I find out if it is needed? Is it enough if it builds without any issues or digging through the source code?

Builds fine, so turns out you don't need that after all :3

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1545
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9993256310) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1547)|

### Manual backport
To create the backport manually run:
```
backport --pr 1545
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9993256304) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1546)|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1545
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9993256316) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1546)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1547)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9993256330) for details

**Comment by der-eismann** [comment]
Awesome, thanks for the quick merge!

**Pull request merged**
