### PR TITLE
fix: kotlin

### PR DESCRIPTION
**Pull request by sadlerm4**

### CODE REVIEW

**Review by madonuko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2657)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2658)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2659)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2660)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12367222028) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2657)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2659)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2660)|

### Manual backport
To create the backport manually run:
```
backport --pr 2656
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12367221397) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2657)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2658)|
|❌|f41|An unhandled error occurred. Please see the logs for details|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2660)|

### Manual backport
To create the backport manually run:
```
backport --pr 2656
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12367221992) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2657)|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2659)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2660)|

### Manual backport
To create the backport manually run:
```
backport --pr 2656
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12367222014) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/2657)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/2658)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/2659)|
|✅|el10|[](https://github.com/terrapkg/packages/pull/2660)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12367222016) for details

**Pull request merged**
