### PR TITLE
fix(unitycore): fix linkage

### PR DESCRIPTION
**Pull request by cat-master21**
Not sure why, but it appears that libdir was broken.

### CODE REVIEW

**Review by lleyton — DISMISSED** [review]

**Comment by lleyton** [comment]
Hm, I'm going to build a new Terra builder image, hopefully it fixes that weird rpmfusion gpg error.

**Comment by lleyton** [comment]
Weird... so it's only happening on this package (even on the version on main). It's probably pulling something from rpmfusion.. is that intensional?

**Comment by cat-master21** [comment]
No it should not be doing so, I built this package without RPMFusion and without others (like electron).

**Comment by lleyton** [comment]
Alrightie, we decided to get rid of rpmfusion from the Mock build environment, it was causing issues with some other packages. We'll try a run again once the new image is done building.

**Comment by lleyton** [comment]
Alrightie, could you check the latest build?

**Review by madonuko — APPROVED** [review]

**Pull request merged**
