### PR TITLE
rm: terra-mesa

### PR DESCRIPTION
**Pull request by madonuko**
This is temporary and prevents potential conflicts with Fedora.

### CODE REVIEW

**Review by lleyton — APPROVED** [review]

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f39:<br> - [fix(update): crystal (#1571)](https://github.com/terrapkg/packages/pull/1571)|
|❌|f40|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to f40:<br> - [fix(update): crystal (#1571)](https://github.com/terrapkg/packages/pull/1571)|

### Manual backport
To create the backport manually run:
```
backport --pr 1587
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10018190724) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1587
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10018242961) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1587
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10018242968) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1587
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10018242966) for details

**Comment by raboneko** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|Backport failed because of merge conflicts|
|❌|f40|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 1587
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10018243708) for details

**Comment by lleyton** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1591)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1592)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
