### PR TITLE
fix(neovide)!: requires neovim > 0.9.5

### PR DESCRIPTION
**Pull request by madonuko**
https://bodhi.fedoraproject.org/updates/FEDORA-2024-e80df46e2a

### CODE REVIEW

**Review by lleyton — APPROVED** [review]

**Comment by lleyton** [comment]
backport?

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1289)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1290)|

### Manual backport
To create the backport manually run:
```
backport --pr 1286
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9188288839) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1288)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1289)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1290)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9188288889) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1288)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1289)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1290)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9188288837) for details

**Pull request merged**
