### PR TITLE
feat(comps): add `helium` group

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]
great idea

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1281)|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|❌|f40|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1280
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9175635172) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f38|[](https://github.com/terrapkg/packages/pull/1281)|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1282)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1283)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9175635174) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f38|An unhandled error occurred. Please see the logs for details|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1282)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1283)|

### Manual backport
To create the backport manually run:
```
backport --pr 1280
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9175635170) for details

**Pull request merged**
