### PR TITLE
fix: gamescope-session

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — APPROVED** [review]

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1765)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1766)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1767)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1768)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10147803467) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f39|An unhandled error occurred. Please see the logs for details|
|❌|f40|An unhandled error occurred. Please see the logs for details|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1767)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1768)|

### Manual backport
To create the backport manually run:
```
backport --pr 1755
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10147803455) for details

**Comment by raboneko** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1765)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1766)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1767)|
|❌|el9|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 1755
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10147803429) for details

**Comment by raboneko** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[](https://github.com/terrapkg/packages/pull/1765)|
|✅|f40|[](https://github.com/terrapkg/packages/pull/1766)|
|✅|f41|[](https://github.com/terrapkg/packages/pull/1767)|
|✅|el9|[](https://github.com/terrapkg/packages/pull/1768)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10147803434) for details

**Pull request merged**
